### ISSUE TITLE
no issue, just a request

### ISSUE THREAD

**Issue by devalanche** [PRATAP-KUMAR/focal_gdm3_login_theme_complete_hack#1] opened 2020-05-01 12:37 UTC
hi, thanks for your awesome scripts!
No idea if it is possible in 20.04 but in 19.10 we've been able to change the screen between logging in and loading the desktop.
Do you see any chance to make that happen in 20.04 as well?
For 19.10 I recently used those steps:

1.) download the scripts on the DevPy GitHub: devpytech/scripts/gresource-extract
2.) run ./extract.sh to extract your current theme to the "theme" folder in the same folder as the extract script
3.) edit ./theme/gnome-shell.css (change #lockDialogGroup)
background: #000000 url(resource:///org/gnome/shell/theme/noise-texture.png);
4.) copy background image to ./theme/noise-texture.png (i.e., use same name)
5.) run ./build.sh from DevPy's GitHub to create .gresource file in the theme folder
6.) sudo mv ./theme/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource

But yea, no effect in Focal Fossa... I'm not as deep in linux and gnome shell as you are, so you are my hope to finally get rid of the ugly ubuntu purple without messing around with alternative themes or desktops.

Please let me know if I can support you in any way :)

**Comment by PRATAP-KUMAR** [comment] 2020-05-01 12:41
sure rite now i am on mobile.. read your words twice.. still need to read in system and I will try in an hour. Thanks for your words.. will get back soon!!!

**Comment by PRATAP-KUMAR** [comment] 2020-05-01 12:59
Hi, I have gone through your 6 steps and I have executed 6th step. Did you do this in Ubuntu 19.10 or Other OS? Please respond to proceed further.

**Comment by devalanche** [comment] 2020-05-01 13:05
Hi, I did this on 19.10 only yet

**Comment by devalanche** [comment] 2020-05-01 13:06
here is the source I have those steps from, seem like they have been working since 17.10

https://ubuntuforums.org/showthread.php?t=2384043&p=13736129#post13736129

**Comment by PRATAP-KUMAR** [comment] 2020-05-01 13:07
Hi thanks for response.. Please clarify.. at login screen you have purple color by default. when you enter your pwd and hit enter.. you will see less than a second purple color and then your desktop. are you talking about this less than a second one?

**Comment by devalanche** [comment] 2020-05-01 13:07
yes exactly, this tiny second is driving me crazy :D

**Comment by PRATAP-KUMAR** [comment] 2020-05-01 13:10
Ok its clear now. so give me some time so that I will install Ubuntu 19.10 and reproduce it. Then in 20.04 I will see. Make sure I am on this job. Will respond back after attempting it. Thanks for the clarity and links..

**Comment by devalanche** [comment] 2020-05-01 13:12
Wow, cool guy, good luck!!

**Comment by PRATAP-KUMAR** [comment] 2020-05-01 14:29
Hi, I did install Ubuntu 19.10 and did all the steps in the link you provided. grub, plymouth have changed to black. login background, lockscreen background and flash between login screen -->> desktop transition is still purple.. can you think about my Question in above comments.. are you using Ubuntu 19.10 or Other OS? you answered 19.10.. Please confirm Ubuntu 19.10 or not?

**Comment by devalanche** [comment] 2020-05-01 14:35
I was using Ubuntu 19.10 for sure. 
Did you do the gresource stuff with your own theme extraction? When I did the 6 steps I had to delete the themes directory that was coming with the repo clone before I extract my data, then modify the img and css, after that building and moving did the trick for me.

https://github.com/devpytech/scripts/tree/master/gresource-extract look here, the themes folder should be empty before doing the magic

**Comment by PRATAP-KUMAR** [comment] 2020-05-01 15:06
hum... there must be a trick really bcoz you have achieved this with Ubuntu 19.10. I am surprised bcoz Ubuntu 19.10 or starting from 17.10 no OS uses the `.gresource` file we are building for customizing the login background nor the flick color. the usage of this newly built `.gresource` from the extract and build scripts is possible only if we do some more configurations.. Otherwise in 19.10 `/usr/share/gnome-shell/theme/Yaru/gnome-shell.css`

````
$ update-alternatives --config gdm3.css 
There are 2 choices for the alternative gdm3.css (providing /usr/share/gnome-shell/theme/gdm3.css).

  Selection    Path                                               Priority   Status
------------------------------------------------------------
* 0            /usr/share/gnome-shell/theme/Yaru/gnome-shell.css   15        auto mode
  1            /usr/share/gnome-shell/theme/Yaru/gnome-shell.css   15        manual mode
  2            /usr/share/gnome-shell/theme/gnome-shell.css        10        manual mode

Press <enter> to keep the current choice[*], or type selection number: 
$
````

**Comment by PRATAP-KUMAR** [comment] 2020-05-01 15:33
https://askubuntu.com/q/1127236/739431

**Comment by PRATAP-KUMAR** [comment] 2020-05-01 15:48
Ok.. got the point.... "the small tiny second" background is using the background `noise-texture.png` from the built up `gnome-shell-theme.gresource` file. Yes I agree in Ubuntu 19.10 it is possible.

**Comment by devalanche** [comment] 2020-05-01 15:53
ok, sorry for the confusion :S

**Comment by PRATAP-KUMAR** [comment] 2020-05-01 15:56
no no "no sorry.." Its pretty clear now or who read our post.. Ok now I am going to install 20.04 and see whats happening.. but its already 9:25PM.. I may go to sleep.. definitely will get back to you soon.

**Comment by devalanche** [comment] 2020-05-01 15:58
ok, sleep well, and no hurry :)

**Comment by PRATAP-KUMAR** [comment] 2020-05-02 13:30
Hi, I tried it in Ubuntu 20.04 and seems in 20.04 lot of good changes happened in which one of the change is no more depending on that `noise-texture.png`. I am trying a workaround to get rid of that purple color and in final testing stage.. in 2 days will post you the workaround. Thanks!!!

**Comment by devalanche** [comment] 2020-05-02 13:49
Hey, that’s great news! Thank you for your time and efforts!

**Comment by PRATAP-KUMAR** [comment] 2020-05-03 00:38
Hi are you online??

**Comment by devalanche** [comment] 2020-05-03 22:18
semi, already in bed :D why?

**Comment by PRATAP-KUMAR** [comment] 2020-05-04 00:20
the work around is ready. ok when you r ready to test it ping me in the morning..

**Comment by devalanche** [comment] 2020-05-04 06:21
good morning, ok what shall I do?

**Comment by PRATAP-KUMAR** [comment] 2020-05-04 06:25
Hi, good morning.. the workaround is to install [ this gnome-shell-extension ](https://extensions.gnome.org/extension/3037/good-bye-gdm-flick/)

**Comment by devalanche** [comment] 2020-05-04 06:35
hmm, for me it is not working, I still have that purple flick screen

**Comment by PRATAP-KUMAR** [comment] 2020-05-04 06:51
Hi U tried in Ubuntu 20.04 0r 19.10?

**Comment by devalanche** [comment] 2020-05-04 06:53
20.04 with standard yaru-dark as well as user theme adwaite-gray-dark (and shell theme adwaita-gray-dark)

**Comment by PRATAP-KUMAR** [comment] 2020-05-04 06:56
I did install this extension in few pcs.. tested under root user and regular users too.. whats the output of `gnome-extensions list` and then `gnome-extensions show <uuid0ftheextension>`

**Comment by devalanche** [comment] 2020-05-04 06:58
dim-on-battery@nailfarmer.nailfarmer.com
docker-containers@jurix-hackbay
wattmeter@bb
disable-animations-on-battery@rliang.github.com
disconnect-wifi@kgshank.net
refresh-wifi@kgshank.net
BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm
bluetooth-quick-connect@bjarosze.gmail.com
goodbyegdmflick@pratap.fastmail.fm
update-extensions@franglais125.gmail.com
add-on-desktop@maestroschan.fr
fq@megh
workspace-switch-wraparound@theychx.org
desktop-icons@csoriano
ubuntu-appindicators@ubuntu.com
ubuntu-dock@ubuntu.com
apps-menu@gnome-shell-extensions.gcampax.github.com
auto-move-windows@gnome-shell-extensions.gcampax.github.com
drive-menu@gnome-shell-extensions.gcampax.github.com
horizontal-workspaces@gnome-shell-extensions.gcampax.github.com
launch-new-instance@gnome-shell-extensions.gcampax.github.com
native-window-placement@gnome-shell-extensions.gcampax.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
windowsNavigator@gnome-shell-extensions.gcampax.github.com
workspace-indicator@gnome-shell-extensions.gcampax.github.com

**Comment by devalanche** [comment] 2020-05-04 06:59
goodbyegdmflick@pratap.fastmail.fm
  Name: Good Bye GDM3 Login Screen to Desktop Flick
  Description: No Flickering Between GDM3 Login Screen to Desktop Transition. Generally you will notice a Ubuntu's purple or Grey color Flick when you type your password and hit enter. With this Extension you will not have that flick. your Login Background and your Desktop Background.
  Path: /home/devalanche/.local/share/gnome-shell/extensions/goodbyegdmflick@pratap.fastmail.fm
  URL: 
  Version: 1
  State: ENABLED

**Comment by PRATAP-KUMAR** [comment] 2020-05-04 07:03
0k thats nice.. seems everything ok with your outputs.. let me dig more why its nit working for you.. I will try in some other pcs.. thanks for yor response..

**Comment by devalanche** [comment] 2020-05-04 07:04
if you want you can use anydesk or so to dig in my linux installation

**Comment by PRATAP-KUMAR** [comment] 2020-05-04 07:06
ya thanks for it.. but seems few more details are enough.. is it a fresh install 20.04 0r Upgraded?

**Comment by devalanche** [comment] 2020-05-04 07:16
upgraded

**Comment by PRATAP-KUMAR** [comment] 2020-05-04 08:23
Hi, I have checked in other fresh install of 20.04. Extension works fine. I think updates generally have some conflicts.. Before digging upgrade vs fresh install, I would like you to check the extension with fresh install of Ubuntu 20.04 where possible.

**Comment by devalanche** [comment] 2020-05-04 08:26
yea ok, I will do that, but it will take some days I guess, since I am pretty busy atm :/

**Comment by PRATAP-KUMAR** [comment] 2020-05-04 12:32
Hi, Can you check the animation in this [ link ](https://extensions.gnome.org/extension/3037/good-bye-gdm-flick/) and from this [ link ](https://i.stack.imgur.com/EzbFr.gif)

Points to observe:
1. Dark Green is Login Background
2. Ubuntu's Purple is the Flick
3. Blue is Desktop Background..

**Comment by devalanche** [comment] 2020-05-04 14:00
My battery went down in the meanwhile, after plugging it in and booting up, it worked :D

**Comment by devalanche** [comment] 2020-05-04 14:00
Thank you for your hard work! Can I spend a beer for you?

**Comment by PRATAP-KUMAR** [comment] 2020-05-04 14:03
Thanks for confirming.. I was bit upset since it didn't work for you. but happy now with your confirmation. yup once corana goes away I would like to have beer offer.. tempting beer.. chill.. Ok lets delete the chat rite??

**Comment by devalanche** [comment] 2020-05-04 14:07
I rebooted several times earlier when it didnt work, no idea why it worked now... anyway, I'm very sorry for that weird behavior. Today is a weird day, I encounter a lot of weird stuff today, dunno what that is.

Yea lets delete the chat. Thanks again! Many many thanks! :)

**Closed** 2020-05-04 14:09 UTC

**Comment by PRATAP-KUMAR** [comment] 2020-10-31 04:58
Hi, How are you? I am trying to achieve to change the color or an Image in place of the default purple color. in past, The extension I shared to you is just skipping that 0.5secs flick.. I would like to know from you, is that extension still satisfactory?
